// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileInfo is an autogenerated mock type for the FileInfo type
type FileInfo struct {
	mock.Mock
}

type FileInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *FileInfo) EXPECT() *FileInfo_Expecter {
	return &FileInfo_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *FileInfo) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// FileInfo_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type FileInfo_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *FileInfo_Expecter) Name() *FileInfo_Name_Call {
	return &FileInfo_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *FileInfo_Name_Call) Run(run func()) *FileInfo_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileInfo_Name_Call) Return(_a0 string) *FileInfo_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileInfo_Name_Call) RunAndReturn(run func() string) *FileInfo_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function with given fields:
func (_m *FileInfo) Size() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// FileInfo_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type FileInfo_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *FileInfo_Expecter) Size() *FileInfo_Size_Call {
	return &FileInfo_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *FileInfo_Size_Call) Run(run func()) *FileInfo_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileInfo_Size_Call) Return(_a0 int64) *FileInfo_Size_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileInfo_Size_Call) RunAndReturn(run func() int64) *FileInfo_Size_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileInfo creates a new instance of FileInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileInfo {
	mock := &FileInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
