// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	storage "github.com/flatmix/final-otus-project/internal/migrator/storage"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/flatmix/final-otus-project/internal/migrator/usecase"
)

// UCContract is an autogenerated mock type for the UCContract type
type UCContract struct {
	mock.Mock
}

type UCContract_Expecter struct {
	mock *mock.Mock
}

func (_m *UCContract) EXPECT() *UCContract_Expecter {
	return &UCContract_Expecter{mock: &_m.Mock}
}

// CreateMigration provides a mock function with given fields: ctx, file, version
func (_m *UCContract) CreateMigration(ctx context.Context, file usecase.FileStruct, version int) error {
	ret := _m.Called(ctx, file, version)

	if len(ret) == 0 {
		panic("no return value specified for CreateMigration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.FileStruct, int) error); ok {
		r0 = rf(ctx, file, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UCContract_CreateMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMigration'
type UCContract_CreateMigration_Call struct {
	*mock.Call
}

// CreateMigration is a helper method to define mock.On call
//   - ctx context.Context
//   - file usecase.FileStruct
//   - version int
func (_e *UCContract_Expecter) CreateMigration(ctx interface{}, file interface{}, version interface{}) *UCContract_CreateMigration_Call {
	return &UCContract_CreateMigration_Call{Call: _e.mock.On("CreateMigration", ctx, file, version)}
}

func (_c *UCContract_CreateMigration_Call) Run(run func(ctx context.Context, file usecase.FileStruct, version int)) *UCContract_CreateMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.FileStruct), args[2].(int))
	})
	return _c
}

func (_c *UCContract_CreateMigration_Call) Return(_a0 error) *UCContract_CreateMigration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UCContract_CreateMigration_Call) RunAndReturn(run func(context.Context, usecase.FileStruct, int) error) *UCContract_CreateMigration_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMigrationsTable provides a mock function with given fields: ctx
func (_m *UCContract) CreateMigrationsTable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateMigrationsTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UCContract_CreateMigrationsTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMigrationsTable'
type UCContract_CreateMigrationsTable_Call struct {
	*mock.Call
}

// CreateMigrationsTable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UCContract_Expecter) CreateMigrationsTable(ctx interface{}) *UCContract_CreateMigrationsTable_Call {
	return &UCContract_CreateMigrationsTable_Call{Call: _e.mock.On("CreateMigrationsTable", ctx)}
}

func (_c *UCContract_CreateMigrationsTable_Call) Run(run func(ctx context.Context)) *UCContract_CreateMigrationsTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UCContract_CreateMigrationsTable_Call) Return(_a0 error) *UCContract_CreateMigrationsTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UCContract_CreateMigrationsTable_Call) RunAndReturn(run func(context.Context) error) *UCContract_CreateMigrationsTable_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMigration provides a mock function with given fields: ctx, file
func (_m *UCContract) DeleteMigration(ctx context.Context, file usecase.FileStruct) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMigration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.FileStruct) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UCContract_DeleteMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMigration'
type UCContract_DeleteMigration_Call struct {
	*mock.Call
}

// DeleteMigration is a helper method to define mock.On call
//   - ctx context.Context
//   - file usecase.FileStruct
func (_e *UCContract_Expecter) DeleteMigration(ctx interface{}, file interface{}) *UCContract_DeleteMigration_Call {
	return &UCContract_DeleteMigration_Call{Call: _e.mock.On("DeleteMigration", ctx, file)}
}

func (_c *UCContract_DeleteMigration_Call) Run(run func(ctx context.Context, file usecase.FileStruct)) *UCContract_DeleteMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.FileStruct))
	})
	return _c
}

func (_c *UCContract_DeleteMigration_Call) Return(_a0 error) *UCContract_DeleteMigration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UCContract_DeleteMigration_Call) RunAndReturn(run func(context.Context, usecase.FileStruct) error) *UCContract_DeleteMigration_Call {
	_c.Call.Return(run)
	return _c
}

// ExistTable provides a mock function with given fields: ctx, schema, table
func (_m *UCContract) ExistTable(ctx context.Context, schema string, table string) bool {
	ret := _m.Called(ctx, schema, table)

	if len(ret) == 0 {
		panic("no return value specified for ExistTable")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, schema, table)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// UCContract_ExistTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistTable'
type UCContract_ExistTable_Call struct {
	*mock.Call
}

// ExistTable is a helper method to define mock.On call
//   - ctx context.Context
//   - schema string
//   - table string
func (_e *UCContract_Expecter) ExistTable(ctx interface{}, schema interface{}, table interface{}) *UCContract_ExistTable_Call {
	return &UCContract_ExistTable_Call{Call: _e.mock.On("ExistTable", ctx, schema, table)}
}

func (_c *UCContract_ExistTable_Call) Run(run func(ctx context.Context, schema string, table string)) *UCContract_ExistTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UCContract_ExistTable_Call) Return(_a0 bool) *UCContract_ExistTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UCContract_ExistTable_Call) RunAndReturn(run func(context.Context, string, string) bool) *UCContract_ExistTable_Call {
	_c.Call.Return(run)
	return _c
}

// GetActualVersion provides a mock function with given fields: ctx
func (_m *UCContract) GetActualVersion(ctx context.Context) int {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActualVersion")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// UCContract_GetActualVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActualVersion'
type UCContract_GetActualVersion_Call struct {
	*mock.Call
}

// GetActualVersion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UCContract_Expecter) GetActualVersion(ctx interface{}) *UCContract_GetActualVersion_Call {
	return &UCContract_GetActualVersion_Call{Call: _e.mock.On("GetActualVersion", ctx)}
}

func (_c *UCContract_GetActualVersion_Call) Run(run func(ctx context.Context)) *UCContract_GetActualVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UCContract_GetActualVersion_Call) Return(_a0 int) *UCContract_GetActualVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UCContract_GetActualVersion_Call) RunAndReturn(run func(context.Context) int) *UCContract_GetActualVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllMigrationFile provides a mock function with given fields:
func (_m *UCContract) GetAllMigrationFile() ([]usecase.FileStruct, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllMigrationFile")
	}

	var r0 []usecase.FileStruct
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]usecase.FileStruct, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []usecase.FileStruct); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usecase.FileStruct)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCContract_GetAllMigrationFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMigrationFile'
type UCContract_GetAllMigrationFile_Call struct {
	*mock.Call
}

// GetAllMigrationFile is a helper method to define mock.On call
func (_e *UCContract_Expecter) GetAllMigrationFile() *UCContract_GetAllMigrationFile_Call {
	return &UCContract_GetAllMigrationFile_Call{Call: _e.mock.On("GetAllMigrationFile")}
}

func (_c *UCContract_GetAllMigrationFile_Call) Run(run func()) *UCContract_GetAllMigrationFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCContract_GetAllMigrationFile_Call) Return(_a0 []usecase.FileStruct, _a1 error) *UCContract_GetAllMigrationFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCContract_GetAllMigrationFile_Call) RunAndReturn(run func() ([]usecase.FileStruct, error)) *UCContract_GetAllMigrationFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllMigrationFileMap provides a mock function with given fields:
func (_m *UCContract) GetAllMigrationFileMap() (usecase.FilesMap, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllMigrationFileMap")
	}

	var r0 usecase.FilesMap
	var r1 error
	if rf, ok := ret.Get(0).(func() (usecase.FilesMap, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() usecase.FilesMap); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usecase.FilesMap)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCContract_GetAllMigrationFileMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMigrationFileMap'
type UCContract_GetAllMigrationFileMap_Call struct {
	*mock.Call
}

// GetAllMigrationFileMap is a helper method to define mock.On call
func (_e *UCContract_Expecter) GetAllMigrationFileMap() *UCContract_GetAllMigrationFileMap_Call {
	return &UCContract_GetAllMigrationFileMap_Call{Call: _e.mock.On("GetAllMigrationFileMap")}
}

func (_c *UCContract_GetAllMigrationFileMap_Call) Run(run func()) *UCContract_GetAllMigrationFileMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCContract_GetAllMigrationFileMap_Call) Return(_a0 usecase.FilesMap, _a1 error) *UCContract_GetAllMigrationFileMap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCContract_GetAllMigrationFileMap_Call) RunAndReturn(run func() (usecase.FilesMap, error)) *UCContract_GetAllMigrationFileMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllMigrationsOrderByVersionDesc provides a mock function with given fields: ctx, step
func (_m *UCContract) GetAllMigrationsOrderByVersionDesc(ctx context.Context, step int) (storage.MigrationsDBStruct, error) {
	ret := _m.Called(ctx, step)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMigrationsOrderByVersionDesc")
	}

	var r0 storage.MigrationsDBStruct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (storage.MigrationsDBStruct, error)); ok {
		return rf(ctx, step)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) storage.MigrationsDBStruct); ok {
		r0 = rf(ctx, step)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.MigrationsDBStruct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, step)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCContract_GetAllMigrationsOrderByVersionDesc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMigrationsOrderByVersionDesc'
type UCContract_GetAllMigrationsOrderByVersionDesc_Call struct {
	*mock.Call
}

// GetAllMigrationsOrderByVersionDesc is a helper method to define mock.On call
//   - ctx context.Context
//   - step int
func (_e *UCContract_Expecter) GetAllMigrationsOrderByVersionDesc(ctx interface{}, step interface{}) *UCContract_GetAllMigrationsOrderByVersionDesc_Call {
	return &UCContract_GetAllMigrationsOrderByVersionDesc_Call{Call: _e.mock.On("GetAllMigrationsOrderByVersionDesc", ctx, step)}
}

func (_c *UCContract_GetAllMigrationsOrderByVersionDesc_Call) Run(run func(ctx context.Context, step int)) *UCContract_GetAllMigrationsOrderByVersionDesc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *UCContract_GetAllMigrationsOrderByVersionDesc_Call) Return(_a0 storage.MigrationsDBStruct, _a1 error) *UCContract_GetAllMigrationsOrderByVersionDesc_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCContract_GetAllMigrationsOrderByVersionDesc_Call) RunAndReturn(run func(context.Context, int) (storage.MigrationsDBStruct, error)) *UCContract_GetAllMigrationsOrderByVersionDesc_Call {
	_c.Call.Return(run)
	return _c
}

// GetDownPart provides a mock function with given fields: fileStruct
func (_m *UCContract) GetDownPart(fileStruct usecase.FileStruct) (string, error) {
	ret := _m.Called(fileStruct)

	if len(ret) == 0 {
		panic("no return value specified for GetDownPart")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(usecase.FileStruct) (string, error)); ok {
		return rf(fileStruct)
	}
	if rf, ok := ret.Get(0).(func(usecase.FileStruct) string); ok {
		r0 = rf(fileStruct)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(usecase.FileStruct) error); ok {
		r1 = rf(fileStruct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCContract_GetDownPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDownPart'
type UCContract_GetDownPart_Call struct {
	*mock.Call
}

// GetDownPart is a helper method to define mock.On call
//   - fileStruct usecase.FileStruct
func (_e *UCContract_Expecter) GetDownPart(fileStruct interface{}) *UCContract_GetDownPart_Call {
	return &UCContract_GetDownPart_Call{Call: _e.mock.On("GetDownPart", fileStruct)}
}

func (_c *UCContract_GetDownPart_Call) Run(run func(fileStruct usecase.FileStruct)) *UCContract_GetDownPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(usecase.FileStruct))
	})
	return _c
}

func (_c *UCContract_GetDownPart_Call) Return(_a0 string, _a1 error) *UCContract_GetDownPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCContract_GetDownPart_Call) RunAndReturn(run func(usecase.FileStruct) (string, error)) *UCContract_GetDownPart_Call {
	_c.Call.Return(run)
	return _c
}

// GetHash provides a mock function with given fields: fileName
func (_m *UCContract) GetHash(fileName string) (string, error) {
	ret := _m.Called(fileName)

	if len(ret) == 0 {
		panic("no return value specified for GetHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(fileName)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(fileName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCContract_GetHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHash'
type UCContract_GetHash_Call struct {
	*mock.Call
}

// GetHash is a helper method to define mock.On call
//   - fileName string
func (_e *UCContract_Expecter) GetHash(fileName interface{}) *UCContract_GetHash_Call {
	return &UCContract_GetHash_Call{Call: _e.mock.On("GetHash", fileName)}
}

func (_c *UCContract_GetHash_Call) Run(run func(fileName string)) *UCContract_GetHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *UCContract_GetHash_Call) Return(_a0 string, _a1 error) *UCContract_GetHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCContract_GetHash_Call) RunAndReturn(run func(string) (string, error)) *UCContract_GetHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetMigrationRow provides a mock function with given fields: ctx, file
func (_m *UCContract) GetMigrationRow(ctx context.Context, file usecase.FileStruct) (*storage.MigrationDBStruct, error) {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for GetMigrationRow")
	}

	var r0 *storage.MigrationDBStruct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.FileStruct) (*storage.MigrationDBStruct, error)); ok {
		return rf(ctx, file)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.FileStruct) *storage.MigrationDBStruct); ok {
		r0 = rf(ctx, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.MigrationDBStruct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.FileStruct) error); ok {
		r1 = rf(ctx, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCContract_GetMigrationRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMigrationRow'
type UCContract_GetMigrationRow_Call struct {
	*mock.Call
}

// GetMigrationRow is a helper method to define mock.On call
//   - ctx context.Context
//   - file usecase.FileStruct
func (_e *UCContract_Expecter) GetMigrationRow(ctx interface{}, file interface{}) *UCContract_GetMigrationRow_Call {
	return &UCContract_GetMigrationRow_Call{Call: _e.mock.On("GetMigrationRow", ctx, file)}
}

func (_c *UCContract_GetMigrationRow_Call) Run(run func(ctx context.Context, file usecase.FileStruct)) *UCContract_GetMigrationRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.FileStruct))
	})
	return _c
}

func (_c *UCContract_GetMigrationRow_Call) Return(_a0 *storage.MigrationDBStruct, _a1 error) *UCContract_GetMigrationRow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCContract_GetMigrationRow_Call) RunAndReturn(run func(context.Context, usecase.FileStruct) (*storage.MigrationDBStruct, error)) *UCContract_GetMigrationRow_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpPart provides a mock function with given fields: fileStruct
func (_m *UCContract) GetUpPart(fileStruct usecase.FileStruct) (string, error) {
	ret := _m.Called(fileStruct)

	if len(ret) == 0 {
		panic("no return value specified for GetUpPart")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(usecase.FileStruct) (string, error)); ok {
		return rf(fileStruct)
	}
	if rf, ok := ret.Get(0).(func(usecase.FileStruct) string); ok {
		r0 = rf(fileStruct)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(usecase.FileStruct) error); ok {
		r1 = rf(fileStruct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCContract_GetUpPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpPart'
type UCContract_GetUpPart_Call struct {
	*mock.Call
}

// GetUpPart is a helper method to define mock.On call
//   - fileStruct usecase.FileStruct
func (_e *UCContract_Expecter) GetUpPart(fileStruct interface{}) *UCContract_GetUpPart_Call {
	return &UCContract_GetUpPart_Call{Call: _e.mock.On("GetUpPart", fileStruct)}
}

func (_c *UCContract_GetUpPart_Call) Run(run func(fileStruct usecase.FileStruct)) *UCContract_GetUpPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(usecase.FileStruct))
	})
	return _c
}

func (_c *UCContract_GetUpPart_Call) Return(_a0 string, _a1 error) *UCContract_GetUpPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCContract_GetUpPart_Call) RunAndReturn(run func(usecase.FileStruct) (string, error)) *UCContract_GetUpPart_Call {
	_c.Call.Return(run)
	return _c
}

// Migrate provides a mock function with given fields: ctx, migrateSQLString
func (_m *UCContract) Migrate(ctx context.Context, migrateSQLString string) error {
	ret := _m.Called(ctx, migrateSQLString)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, migrateSQLString)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UCContract_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type UCContract_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - ctx context.Context
//   - migrateSQLString string
func (_e *UCContract_Expecter) Migrate(ctx interface{}, migrateSQLString interface{}) *UCContract_Migrate_Call {
	return &UCContract_Migrate_Call{Call: _e.mock.On("Migrate", ctx, migrateSQLString)}
}

func (_c *UCContract_Migrate_Call) Run(run func(ctx context.Context, migrateSQLString string)) *UCContract_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UCContract_Migrate_Call) Return(_a0 error) *UCContract_Migrate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UCContract_Migrate_Call) RunAndReturn(run func(context.Context, string) error) *UCContract_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// NewUCContract creates a new instance of UCContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUCContract(t interface {
	mock.TestingT
	Cleanup(func())
}) *UCContract {
	mock := &UCContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
