stages:
  - tests
  - build


test_linter:
  stage: tests
  image: golangci/golangci-lint
  script:
    - golangci-lint run --out-format=junit-xml --timeout 5m > gl-linter-report.xml
  artifacts:
    expire_in: 2 week
    when: always
    reports:
      junit: gl-linter-report.xml
  allow_failure: false

test_unit:
  stage: tests
  image: golang:latest
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)
  allow_failure: false

compile:
  stage: build
  script:
    - mkdir -p bin
    - go build -o bin ./...
  artifacts:
    paths:
      - bin
